### ISSUE TITLE
How to calculate P, R, F1 in your paper?

### ISSUE THREAD

**Issue by txAnnie** [sameenmaruf/acl2020-contextnmt-cataphora#1]
Hello, i am interested in calculating P, R, F1 you mentioned in your paper, but i don't know the detatil of how to calculate it. May you explain it more detailedly?

**Comment by kay-wong** [comment]
Hi Annie, thanks for your interest in our paper. 
To compute the Precision, Recall and F1 scores, we first obtain a set of pronouns from a candidate translation through dictionary matching. From this set, we then compute the clipped count, precision and recall as in [Hardmeier and Federico](http://www.mt-archive.info/IWSLT-2010-Hardmeier.pdf) (equations 2&3). This is in contrast to the set of target words aligned to a source pronoun as in AutoPRF and APT, which may be subject to alignment errors. Hope that helps!
